# Docker compose file for the docker-compose command

version: '3.7'

services:
  app:
    build:
      context: app
    ports:
      - 5000
    networks:
      - backnet
      - frontnet

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - frontnet
    depends_on:
      - app

networks:
  backnet:
  frontnet:
