version: "3.7"

services:
  db:
    container_name: paper_review_db
    image: postgres:latest
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: paper_review
      POSTGRES_USER: moonphase
      POSTGRES_PASSWORD: eclipse
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backnet

  pgadmin:
    container_name: paper_review_pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: moonphase@paperreview.com
      PGADMIN_DEFAULT_USER: moonphase
      PGADMIN_DEFAULT_PASSWORD: eclipse
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
    ports:
      - 5050:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json
    depends_on:
      - db
    networks:
      - backnet

  app:
    container_name: paper_review_app
    build:
      context: flask
      dockerfile: Dockerfile
    volumes:
      - ./flask:/home/moonphase/paper_review
    restart: always
    depends_on:
      db:
        condition: service_healthy
    entrypoint: /home/moonphase/paper_review/boot.sh
    networks:
      - backnet
      - frontnet

  nginx:
    container_name: paper_review_nginx
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    ports:
      - 80:80
    networks:
      - frontnet

networks:
  backnet:
  frontnet:

volumes:
  pgadmin_data:
