version: "3.7"

services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=paper_review
      - POSTGRES_USER=moonphase
      - POSTGRES_PASSWORD=eclipse
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backnet

  app:
    build:
      context: flask
      dockerfile: Dockerfile
    volumes:
      - ./flask:/app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    entrypoint: /app/entrypoint.sh
    networks:
      - backnet
      - frontnet

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    ports:
      - 80:80
    networks:
      - frontnet

networks:
  backnet:
  frontnet:
