version: '3.7'

services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    networks:
      - backnet

  app:
    build:
      context: app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    depends_on:
      - db
    restart: always
    networks:
      - backnet
      - frontnet

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    ports:
      - 80:80
    networks:
      - frontnet

networks:
  backnet:
  frontnet:
