"""CAZZO

Revision ID: 0200f8134137
Revises: d0d1f2280567
Create Date: 2023-05-17 22:39:06.007288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0200f8134137'
down_revision = 'd0d1f2280567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdf', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=256), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdf', schema=None) as batch_op:
        batch_op.drop_column('filename')

    # ### end Alembic commands ###
