"""added PDFTable

Revision ID: 3fc9e36a0875
Revises: 6735d684862a
Create Date: 2023-05-09 07:30:14.096702

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3fc9e36a0875'
down_revision = '6735d684862a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdf_table',
    sa.Column('id', postgresql.BYTEA(), nullable=False),
    sa.Column('vid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['pdf.id'], ),
    sa.ForeignKeyConstraint(['vid'], ['version.vid'], ),
    sa.PrimaryKeyConstraint('id', 'vid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pdf_table')
    # ### end Alembic commands ###
