"""added draft table

Revision ID: 650b71b4fbf4
Revises: ef3acb1c2ec5
Create Date: 2023-05-14 09:23:13.599708

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '650b71b4fbf4'
down_revision = 'ef3acb1c2ec5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft',
    sa.Column('did', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('did')
    )
    op.create_table('draft_pdf',
    sa.Column('pdf_id', postgresql.BYTEA(), nullable=True),
    sa.Column('draft_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['draft_id'], ['draft.did'], ),
    sa.ForeignKeyConstraint(['pdf_id'], ['pdf.id'], )
    )
    with op.batch_alter_table('version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('draft_id', sa.Integer(), nullable=True))
        batch_op.alter_column('project_title',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['draft_id'])
        batch_op.create_foreign_key(None, 'draft', ['draft_id'], ['did'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('version', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('project_title',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
        batch_op.drop_column('draft_id')

    op.drop_table('draft_pdf')
    op.drop_table('draft')
    # ### end Alembic commands ###
