"""updated project table

Revision ID: 6735d684862a
Revises: e9934cde9aca
Create Date: 2023-05-05 16:56:15.417667

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6735d684862a'
down_revision = 'e9934cde9aca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version_number', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('project_name', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('project_description', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('project_state', postgresql.ENUM('Approved', 'Sumbmitted', 'Requires changes', 'Not Approved', name='status_enum'), nullable=True))
        batch_op.drop_column('PDescription')
        batch_op.drop_column('PState')
        batch_op.drop_column('PName')
        batch_op.drop_column('nversion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nversion', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('PName', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('PState', postgresql.ENUM('Approved', 'Sumbmitted', 'Requires changes', 'Not Approved', name='status_enum'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('PDescription', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('project_state')
        batch_op.drop_column('project_description')
        batch_op.drop_column('project_name')
        batch_op.drop_column('version_number')

    # ### end Alembic commands ###
