"""added PDFVersions

Revision ID: 7ac06e4f461a
Revises: 3fc9e36a0875
Create Date: 2023-05-09 08:02:18.743860

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7ac06e4f461a'
down_revision = '3fc9e36a0875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdf_versions',
    sa.Column('id', postgresql.BYTEA(), nullable=False),
    sa.Column('vid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['pdf.id'], ),
    sa.ForeignKeyConstraint(['vid'], ['version.vid'], ),
    sa.PrimaryKeyConstraint('id', 'vid')
    )
    op.drop_table('pdf_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdf_table',
    sa.Column('id', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('vid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['pdf.id'], name='pdf_table_id_fkey'),
    sa.ForeignKeyConstraint(['vid'], ['version.vid'], name='pdf_table_vid_fkey'),
    sa.PrimaryKeyConstraint('id', 'vid', name='pdf_table_pkey')
    )
    op.drop_table('pdf_versions')
    # ### end Alembic commands ###
