"""Added PDF table

Revision ID: c72bcf3b9682
Revises: 
Create Date: 2023-04-28 11:17:23.207821

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c72bcf3b9682'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdf',
    sa.Column('id', postgresql.BYTEA(), nullable=False),
    sa.Column('key', postgresql.BYTEA(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pdf')
    # ### end Alembic commands ###
