"""Sucamelo

Revision ID: d0d1f2280567
Revises: 650b71b4fbf4
Create Date: 2023-05-17 15:05:59.485085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0d1f2280567'
down_revision = '650b71b4fbf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('version', schema=None) as batch_op:
        batch_op.alter_column('draft_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('version', schema=None) as batch_op:
        batch_op.alter_column('draft_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
