"""test

Revision ID: e4807e6d40e1
Revises: 7d546893170f
Create Date: 2023-06-12 14:46:37.391517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4807e6d40e1'
down_revision = '7d546893170f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version_ref', sa.Integer(), nullable=False))
        batch_op.drop_column('version_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version_number', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('version_ref')

    # ### end Alembic commands ###
