"""Added PDF table

Revision ID: ec016f45b99f
Revises: 
Create Date: 2023-04-27 23:22:44.405264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec016f45b99f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdf',
    sa.Column('id', sa.String(length=512), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pdf')
    # ### end Alembic commands ###
